### ISSUE TITLE
Is this repo ready for use?

### ISSUE THREAD

**Issue by shawninder** [noppolp/wondex-chromecast-cordova#1]
Hey noppolp! I stumbled upon this repo and I was wondering if it's ready to be used yet or not. Does anything work? Can I start using it in a project?

Thanks for any info :)

**Comment by noppolp** [comment]
yep, now this repo ready to use for the basic functions which you can see in "chromecast.js"

**Comment by shawninder** [comment]
Nice! Any way to listen for device connection and disconnection?

**Comment by noppolp** [comment]
For now, you can only call "chromecast.isDeviceConnected" to get status of a device

**Comment by shawninder** [comment]
Ok, thanks
